# Generated by Django 5.2.5 on 2025-08-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0002_cartitem_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
